# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright 2024 (r) Yang Xiwen <forbidden405@foxmail.com>

obj-$(CONFIG_PINCTRL_HISTB)		+= pinctrl-histb.o
obj-$(CONFIG_PINCTRL_HI3798MV2X)	+= pinctrl-hi3798mv2x.o
